#!/usr/bin/env python3
"""
Step 5: Complete Leak-Free Entity Resolution Pipeline
  - No 3M truncation: evaluates against the complete target population.
  - Option A: No artificial positive injection (trains strictly on candidates generated by the blocker).
  - Separate S2 and S3 candidate retrieval (Top K_s2 + Top K_s3).
  - Prefix-composite blocker with IDF weighting.
  - Full 25-feature pairwise feature extractor.
  - LightGBM classifier with class_weight='balanced'.
  - Coarse (0.30 to 0.95, step 0.01) + Fine (step 0.001) threshold optimization on Macro F_0.5.
"""

import os
import re
import sys
import math
import time
import unicodedata
from collections import defaultdict
from typing import Dict, List, Set, Tuple
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
try:
    import lightgbm as lgb
    HAS_LGB = True
except ImportError:
    HAS_LGB = False
    from sklearn.ensemble import HistGradientBoostingClassifier

train_dir = r"c:\Users\Shourya\Desktop\dataset\student_resource\dataset\train"

print("="*75)
print("STEP 5: COMPLETE LEAK-FREE PIPELINE (TRAINING, VALIDATION & EVALUATION)")
print("="*75)
sys.stdout.flush()

# ==============================================================================
# 1. PREPROCESSING & NORMALIZATION
# ==============================================================================

LEGAL_SUFFIXES = {
    'pvt ltd', 'private limited', 'pvt', 'ltd', 'limited', 'inc', 'incorporated',
    'corp', 'corporation', 'llc', 'llp', 'co', 'company', 'enterprises', 'enterprise',
    'holding', 'holdings', 'group', 'services', 'solutions', 'technologies', 'tech',
    'industries', 'international', 'intl', 'gmbh', 'sa', 'sarl', 'sas', 'bv', 'nv',
    'plc', 'spa', 'srl', 'sl', 'cia', 'assoc', 'associates',
    'praivet limited', 'praaivett limittedd', 'privat limited', 'praivet', 'pra li',
    'elelpi', 'limitet', 'piraivet limitet', 'piraiveett limittett'
}

ADDR_MAP = {
    'rd': 'road', 'st': 'street', 'ave': 'avenue', 'av': 'avenue', 'blvd': 'boulevard',
    'ln': 'lane', 'dr': 'drive', 'ct': 'court', 'pl': 'place', 'sq': 'square',
    'hwy': 'highway', 'pkwy': 'parkway', 'fl': 'floor', 'flr': 'floor', 'apt': 'apartment',
    'ste': 'suite', 'bldg': 'building', 'opp': 'opposite', 'nr': 'near', 'dist': 'district',
    'teh': 'tehsil', 'taluk': 'taluka', 'stn': 'station', 'nagar': 'nagar', 'marg': 'marg'
}

try:
    import anyascii
    def transliterate_text(text: str) -> str:
        return anyascii.anyascii(text) if text else ""
except ImportError:
    try:
        import unidecode
        def transliterate_text(text: str) -> str:
            return unidecode.unidecode(text) if text else ""
    except ImportError:
        def transliterate_text(text: str) -> str:
            return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8') if text else ""

def normalize_text_general(text: str) -> str:
    if not isinstance(text, str) or not text.strip():
        return ""
    text = unicodedata.normalize('NFKC', text)
    if any(ord(c) >= 128 for c in text):
        text = transliterate_text(text)
    text = text.lower()
    text = re.sub(r'&', ' and ', text)
    text = re.sub(r'[/\\_\-+,.:;!?\'"()\[\]{}|@#*^~`]', ' ', text)
    return ' '.join(text.split())

def clean_name_and_core(name: str) -> Tuple[str, str]:
    cleaned = normalize_text_general(name)
    tokens = cleaned.split()
    core_tokens = list(tokens)
    while len(core_tokens) > 1:
        if len(core_tokens) >= 2 and f"{core_tokens[-2]} {core_tokens[-1]}" in LEGAL_SUFFIXES:
            core_tokens = core_tokens[:-2]
        elif core_tokens[-1] in LEGAL_SUFFIXES:
            core_tokens = core_tokens[:-1]
        else:
            break
    core = ' '.join(core_tokens) if core_tokens else cleaned
    return cleaned, core

def clean_address(addr: str) -> str:
    cleaned = normalize_text_general(addr)
    tokens = cleaned.split()
    return ' '.join([ADDR_MAP.get(t, t) for t in tokens])

def extract_clean_numbers(addr: str) -> List[str]:
    res = []
    for n in re.findall(r'\b\d+\b', addr):
        try:
            norm = str(int(n))
            if 1 <= len(norm) <= 7:
                res.append(norm)
        except ValueError:
            pass
    return res


# ==============================================================================
# 2. STRING SIMILARITY
# ==============================================================================

def levenshtein_ratio(s1: str, s2: str) -> float:
    if s1 == s2: return 1.0
    if not s1 or not s2: return 0.0
    if len(s1) > len(s2): s1, s2 = s2, s1
    distances = list(range(len(s1) + 1))
    for i2, c2 in enumerate(s2):
        new_dist = [i2 + 1]
        for i1, c1 in enumerate(s1):
            if c1 == c2:
                new_dist.append(distances[i1])
            else:
                new_dist.append(1 + min((distances[i1], distances[i1 + 1], new_dist[-1])))
        distances = new_dist
    return 1.0 - (distances[-1] / max(len(s1), len(s2)))

def jaro_winkler_similarity(s1: str, s2: str, p: float = 0.1, max_l: int = 4) -> float:
    if s1 == s2: return 1.0
    len1, len2 = len(s1), len(s2)
    if len1 == 0 or len2 == 0: return 0.0
    match_distance = max(len1, len2) // 2 - 1
    s1_matches = [False] * len1
    s2_matches = [False] * len2
    matches = 0
    transpositions = 0
    for i in range(len1):
        start = max(0, i - match_distance)
        end = min(i + match_distance + 1, len2)
        for j in range(start, end):
            if s2_matches[j] or s1[i] != s2[j]: continue
            s1_matches[i] = True
            s2_matches[j] = True
            matches += 1
            break
    if matches == 0: return 0.0
    k = 0
    for i in range(len1):
        if not s1_matches[i]: continue
        while not s2_matches[k]: k += 1
        if s1[i] != s2[k]: transpositions += 1
        k += 1
    jaro = ((matches / len1) + (matches / len2) + ((matches - transpositions / 2.0) / matches)) / 3.0
    l = 0
    for i in range(min(max_l, min(len1, len2))):
        if s1[i] == s2[i]: l += 1
        else: break
    return jaro + (l * p * (1.0 - jaro))

def get_char_ngrams(s: str, n: int = 3) -> Set[str]:
    s = f"^{s}$"
    if len(s) < n: return {s}
    return {s[i:i+n] for i in range(len(s) - n + 1)}


# ==============================================================================
# 3. 25-FEATURE PAIRWISE VECTOR
# ==============================================================================

def extract_pair_features(s1: dict, tgt: dict, blocking_score: float = 0.0) -> Dict[str, float]:
    s1_name, c_name = s1['clean_name'], tgt['clean_name']
    s1_core, c_core = s1['core_name'], tgt['core_name']
    s1_addr, c_addr = s1['clean_addr'], tgt['clean_addr']

    s1_n_toks, c_n_toks = set(s1_name.split()), set(c_name.split())
    s1_c_toks, c_c_toks = set(s1_core.split()), set(c_core.split())
    s1_a_toks, c_a_toks = set(s1_addr.split()), set(c_addr.split())

    s1_nums, c_nums = set(s1['nums']), set(tgt['nums'])

    n_inter = len(s1_n_toks & c_n_toks)
    n_union = len(s1_n_toks | c_n_toks)
    name_jaccard = n_inter / n_union if n_union > 0 else 0.0

    c_inter = len(s1_c_toks & c_c_toks)
    c_union = len(s1_c_toks | c_c_toks)
    core_jaccard = c_inter / c_union if c_union > 0 else 0.0

    min_n = min(len(s1_n_toks), len(c_n_toks))
    name_containment = n_inter / min_n if min_n > 0 else 0.0

    a_inter = len(s1_a_toks & c_a_toks)
    a_union = len(s1_a_toks | c_a_toks)
    addr_jaccard = a_inter / a_union if a_union > 0 else 0.0
    min_a = min(len(s1_a_toks), len(c_a_toks))
    addr_containment = a_inter / min_a if min_a > 0 else 0.0

    num_inter = len(s1_nums & c_nums)
    num_union = len(s1_nums | c_nums)
    digit_jaccard = num_inter / num_union if num_union > 0 else 0.0

    s1_w0 = s1_core.split()[0] if s1_core else ""
    c_w0 = c_core.split()[0] if c_core else ""
    first_word_match = 1.0 if (s1_w0 and s1_w0 == c_w0) else 0.0
    first_char_match = 1.0 if (s1_name and c_name and s1_name[0] == c_name[0]) else 0.0

    s1_ng = get_char_ngrams(s1_name, 3)
    c_ng = get_char_ngrams(c_name, 3)
    name_char3_jaccard = len(s1_ng & c_ng) / max(1, len(s1_ng | c_ng))

    s1_ang = get_char_ngrams(s1_addr, 3)
    c_ang = get_char_ngrams(c_addr, 3)
    addr_char3_jaccard = len(s1_ang & c_ang) / max(1, len(s1_ang | c_ang))

    return {
        'feat_name_exact': 1.0 if s1_name == c_name else 0.0,
        'feat_core_exact': 1.0 if s1_core == c_core else 0.0,
        'feat_name_lev': levenshtein_ratio(s1_name, c_name),
        'feat_core_lev': levenshtein_ratio(s1_core, c_core),
        'feat_name_jw': jaro_winkler_similarity(s1_name, c_name),
        'feat_core_jw': jaro_winkler_similarity(s1_core, c_core),
        'feat_name_token_jaccard': name_jaccard,
        'feat_core_token_jaccard': core_jaccard,
        'feat_name_containment': name_containment,
        'feat_name_char3_jaccard': name_char3_jaccard,
        'feat_first_word_match': first_word_match,
        'feat_first_char_match': first_char_match,
        'len_name_diff': abs(len(s1_name) - len(c_name)) / max(1, max(len(s1_name), len(c_name))),
        'feat_addr_exact': 1.0 if (s1_addr and s1_addr == c_addr) else 0.0,
        'feat_addr_lev': levenshtein_ratio(s1_addr, c_addr) if (s1_addr and c_addr) else 0.0,
        'feat_addr_jw': jaro_winkler_similarity(s1_addr, c_addr) if (s1_addr and c_addr) else 0.0,
        'feat_addr_token_jaccard': addr_jaccard,
        'feat_addr_containment': addr_containment,
        'feat_addr_char3_jaccard': addr_char3_jaccard,
        'digit_overlap': float(num_inter),
        'digit_jaccard': digit_jaccard,
        'has_common_digit': 1.0 if num_inter > 0 else 0.0,
        'blocking_score': float(blocking_score),
        'is_source2': 1.0 if tgt['id'].startswith('S2-') else 0.0
    }


# ==============================================================================
# 4. COMPOSITE KEY GENERATION
# ==============================================================================

def get_composite_keys(core_name: str, clean_addr: str, nums: List[str]) -> List[str]:
    name_words = core_name.split()
    addr_words = [t for t in clean_addr.split() if t not in {'street', 'st', 'road', 'rd', 'ave', 'avenue', 'suite', 'unit', 'dr', 'drive'}]

    keys = []
    # 1. WN and P3N
    for nw in name_words[:5]:
        for nm in nums[:3]:
            keys.append(f"WN:{nw}_{nm}")
            if len(nw) >= 4:
                keys.append(f"P3N:{nw[:3]}_{nm}")

    # 2. WW
    if len(name_words) >= 2:
        keys.append(f"WW:{name_words[0]}_{name_words[1]}")
        if len(name_words) >= 3:
            keys.append(f"WW:{name_words[0]}_{name_words[2]}")

    # 3. AN
    for aw in addr_words[:3]:
        for nm in nums[:3]:
            keys.append(f"AN:{aw}_{nm}")

    # 4. Standalone W
    for nw in name_words[:4]:
        keys.append(f"W:{nw}")

    return keys


# ==============================================================================
# 5. METRIC COMPUTATION (MACRO F_0.5 WITH SINGLETONS)
# ==============================================================================

def compute_macro_f05(preds_by_s1: Dict[str, List[Tuple[str, float]]], val_gt: Dict[str, Set[str]], all_s1_ids: List[str], threshold: float) -> float:
    f_scores = []
    for s1_id in all_s1_ids:
        true_set = val_gt.get(s1_id, set())
        pred_set = {cid for (cid, p) in preds_by_s1.get(s1_id, []) if p >= threshold}

        if not true_set:
            f_scores.append(1.0 if len(pred_set) == 0 else 0.0)
            continue
        if not pred_set:
            f_scores.append(0.0)
            continue

        tp = len(pred_set & true_set)
        fp = len(pred_set - true_set)
        fn = len(true_set - pred_set)

        prec = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        rec = tp / (tp + fn) if (tp + fn) > 0 else 0.0

        if prec + rec == 0:
            f_scores.append(0.0)
        else:
            f05 = (1.25 * prec * rec) / (0.25 * prec + rec)
            f_scores.append(f05)

    return float(np.mean(f_scores))


# ==============================================================================
# 6. PIPELINE EXECUTION
# ==============================================================================

def main():
    # 1. Load Ground Truth for 15,000 S1 Entities (12,000 train, 3,000 val)
    print("\n--> [1/6] Loading Ground Truth for 15,000 S1 Entities...")
    sys.stdout.flush()
    gt_map = {}
    with open(os.path.join(train_dir, "train_ground_truth.tsv"), "r", encoding="utf-8") as f:
        f.readline()
        for line in f:
            p = line.strip().split('\t')
            if len(p) >= 2 and p[1].strip():
                gt_map[p[0]] = set(p[1].split(','))
            else:
                gt_map[p[0]] = set()
            if len(gt_map) >= 15000:
                break

    all_s1_list = list(gt_map.keys())
    # Strict 80/20 entity-level split
    train_s1_ids, val_s1_ids = train_test_split(all_s1_list, test_size=0.20, random_state=42)
    val_s1_set = set(val_s1_ids)

    val_true_s2 = sum(len([x for x in gt_map[s] if x.startswith('S2-')]) for s in val_s1_ids)
    val_true_s3 = sum(len([x for x in gt_map[s] if x.startswith('S3-')]) for s in val_s1_ids)
    print(f"Entities: Total={len(all_s1_list)}, Train={len(train_s1_ids)}, Validation={len(val_s1_ids)}")
    print(f"Validation Ground Truth Matches to Find: S2={val_true_s2}, S3={val_true_s3} (Total={val_true_s2 + val_true_s3})")
    sys.stdout.flush()

    # 2. Load S1 Records
    print("\n--> [2/6] Loading S1 Records...")
    sys.stdout.flush()
    s1_dict = {}
    all_needed_s1 = set(all_s1_list)
    with open(os.path.join(train_dir, "train_source1.tsv"), "r", encoding="utf-8") as f:
        f.readline()
        for line in f:
            p = line.strip().split('\t')
            if p[0] in all_needed_s1:
                clean_n, core_n = clean_name_and_core(p[1])
                clean_a = clean_address(p[2])
                s1_dict[p[0]] = {
                    'id': p[0], 'clean_name': clean_n, 'core_name': core_n,
                    'clean_addr': clean_a, 'nums': extract_clean_numbers(clean_a),
                    'country': p[3].strip().lower()
                }
            if len(s1_dict) == len(all_needed_s1):
                break

    # 3. Index COMPLETE Target Sources S2 and S3 without 3M truncation
    # To save RAM and avoid storing millions of Python dicts, we only store:
    # 1. idx: (country, key) -> list of integer IDs
    # 2. weights: (country, key) -> float
    # Target records will be fetched on demand or cached for retrieved candidates!
    def build_complete_index(filename, prefix):
        print(f"Indexing COMPLETE target file {filename} ({prefix})...")
        sys.stdout.flush()
        t0 = time.time()
        idx = defaultdict(list)
        count = 0
        path = os.path.join(train_dir, filename)

        with open(path, "r", encoding="utf-8") as f:
            f.readline()
            for line in f:
                p = line.strip().split('\t')
                if len(p) >= 4:
                    int_id = int(p[0][3:])
                    clean_n, core_n = clean_name_and_core(p[1])
                    clean_a = clean_address(p[2])
                    nums = extract_clean_numbers(clean_a)
                    c = p[3].strip().lower()

                    for k in get_composite_keys(core_n, clean_a, nums):
                        idx[(c, k)].append(int_id)
                    count += 1

        N = float(count)
        weights = {}
        for k, id_list in idx.items():
            df = len(id_list)
            if df > 5000: continue
            idf = math.log((N + 1.0) / (df + 1.0))
            if k[1].startswith("WN:") or k[1].startswith("WW:"):
                weights[k] = idf * 2.5
            elif k[1].startswith("P3N:") or k[1].startswith("AN:"):
                weights[k] = idf * 1.5
            else:
                weights[k] = idf

        print(f"  Indexed ALL {count:,} {prefix} records in {time.time() - t0:.2f}s! Valid keys: {len(weights):,}")
        sys.stdout.flush()
        return idx, weights, count

    print("\n--> [3/6] Building Full-Population Inverted Indexes (Zero Truncation)...")
    sys.stdout.flush()
    s2_idx, s2_weights, s2_total_count = build_complete_index("train_source2.tsv", "S2")
    s3_idx, s3_weights, s3_total_count = build_complete_index("train_source3.tsv", "S3")

    # 4. Generate Candidate Pairs (Option A: 100% Blocker Generated, Zero Artificial Injection)
    print("\n--> [4/6] Generating Candidate Pairs via Prefix-Composite Blocker...")
    sys.stdout.flush()

    def query_blocker(s1, idx, weights, prefix, k=35):
        c = s1['country']
        keys = get_composite_keys(s1['core_name'], s1['clean_addr'], s1['nums'])
        scores = defaultdict(float)
        for k_str in keys:
            lookup = (c, k_str)
            if lookup in weights:
                w = weights[lookup]
                for int_id in idx[lookup]:
                    scores[int_id] += w
        return [(f"{prefix}-{x[0]}", x[1]) for x in sorted(scores.items(), key=lambda x: x[1], reverse=True)[:k]]

    val_found_s2 = 0
    val_found_s3 = 0
    val_cands_map = {}
    train_cands_map = {}
    all_needed_target_ids = set()

    t0 = time.time()
    for s1_id in all_s1_list:
        s1 = s1_dict[s1_id]
        true_matches = gt_map[s1_id]
        is_val = s1_id in val_s1_set

        # Independent candidate generation: Top 35 S2 + Top 35 S3
        cands_s2 = query_blocker(s1, s2_idx, s2_weights, "S2", k=35)
        cands_s3 = query_blocker(s1, s3_idx, s3_weights, "S3", k=35)

        s2_ids = {c[0] for c in cands_s2}
        s3_ids = {c[0] for c in cands_s3}
        combined = cands_s2 + cands_s3

        if is_val:
            # 100% BLIND VALIDATION: Pure candidate generation
            val_found_s2 += len(true_matches & s2_ids)
            val_found_s3 += len(true_matches & s3_ids)
            val_cands_map[s1_id] = combined
        else:
            # OPTION A: Strictly train on candidates produced by the blocker!
            # Zero artificial injection, zero artificial blocking_score=5.0!
            train_cands_map[s1_id] = combined

        for cid, _ in combined:
            all_needed_target_ids.add(cid)

    q_time = time.time() - t0
    print(f"Querying completed in {q_time:.2f}s ({len(all_s1_list)/q_time:.0f} entities/s).")
    print(f"Total unique target records needed for feature extraction: {len(all_needed_target_ids):,}")
    sys.stdout.flush()

    total_val_true = val_true_s2 + val_true_s3
    total_val_found = val_found_s2 + val_found_s3
    blind_recall_pct = (total_val_found / total_val_true) * 100.0
    avg_cands_val = sum(len(c) for c in val_cands_map.values()) / len(val_s1_ids)

    print("\n" + "="*60)
    print("BLIND CANDIDATE BLOCKING METRICS (VALIDATION):")
    print(f"  S2 Recall: {val_found_s2}/{val_true_s2} ({val_found_s2/val_true_s2*100:.2f}%)")
    print(f"  S3 Recall: {val_found_s3}/{val_true_s3} ({val_found_s3/val_true_s3*100:.2f}%)")
    print(f"  Overall Blind Recall Ceiling: {total_val_found}/{total_val_true} ({blind_recall_pct:.2f}%)")
    print(f"  Average Candidate Pairs per S1: {avg_cands_val:.1f}")
    print("="*60)
    sys.stdout.flush()

    # Load needed target records
    print("\nStreaming and caching only the needed target records for feature extraction...")
    sys.stdout.flush()
    target_cache = {}
    for filename in ["train_source2.tsv", "train_source3.tsv"]:
        path = os.path.join(train_dir, filename)
        with open(path, "r", encoding="utf-8") as f:
            f.readline()
            for line in f:
                p = line.strip().split('\t')
                if len(p) >= 4 and p[0] in all_needed_target_ids:
                    clean_n, core_n = clean_name_and_core(p[1])
                    clean_a = clean_address(p[2])
                    target_cache[p[0]] = {
                        'id': p[0], 'clean_name': clean_n, 'core_name': core_n,
                        'clean_addr': clean_a, 'nums': extract_clean_numbers(clean_a),
                        'country': p[3].strip().lower()
                    }
                    if len(target_cache) == len(all_needed_target_ids):
                        break
        print(f"  Loaded {len(target_cache):,} / {len(all_needed_target_ids):,} candidate records.")
        sys.stdout.flush()

    # 5. Extract Features for Training and Validation Pairs
    print("\n--> [5/6] Extracting 25 Pairwise Features for Training & Validation...")
    sys.stdout.flush()

    X_train, y_train = [], []
    for s1_id, cand_list in train_cands_map.items():
        s1 = s1_dict[s1_id]
        true_set = gt_map[s1_id]
        for cid, b_score in cand_list:
            if cid in target_cache:
                feats = extract_pair_features(s1, target_cache[cid], b_score)
                lbl = 1 if cid in true_set else 0
                X_train.append(feats)
                y_train.append(lbl)

    val_pair_records = []
    for s1_id, cand_list in val_cands_map.items():
        s1 = s1_dict[s1_id]
        true_set = gt_map[s1_id]
        for cid, b_score in cand_list:
            if cid in target_cache:
                feats = extract_pair_features(s1, target_cache[cid], b_score)
                lbl = 1 if cid in true_set else 0
                val_pair_records.append((s1_id, cid, feats, lbl))

    df_X_train = pd.DataFrame(X_train)
    feature_cols = list(df_X_train.columns)
    pos_train = sum(y_train)
    neg_train = len(y_train) - pos_train

    print(f"Training Pairs: {len(X_train):,} (Positives: {pos_train:,} [{pos_train/len(X_train)*100:.2f}%], Negatives: {neg_train:,})")
    print(f"Validation Pairs: {len(val_pair_records):,}")
    print(f"Feature count: {len(feature_cols)}")
    sys.stdout.flush()

    # Train LightGBM Model
    print("\nTraining LightGBM Classifier (n_estimators=350, lr=0.04, balanced class weights)...")
    sys.stdout.flush()
    t_train = time.time()
    if HAS_LGB:
        clf = lgb.LGBMClassifier(
            n_estimators=350,
            learning_rate=0.04,
            num_leaves=31,
            max_depth=6,
            subsample=0.85,
            colsample_bytree=0.85,
            class_weight='balanced',
            random_state=42,
            verbosity=-1
        )
    else:
        clf = HistGradientBoostingClassifier(max_iter=350, learning_rate=0.05, class_weight='balanced', random_state=42)

    clf.fit(df_X_train[feature_cols], np.array(y_train))
    print(f"Model trained in {time.time() - t_train:.2f}s.")
    sys.stdout.flush()

    # Feature Importances
    if HAS_LGB:
        print("\nTop 10 Feature Importances:")
        imp_df = pd.DataFrame({'feature': feature_cols, 'importance': clf.feature_importances_}).sort_values('importance', ascending=False)
        for _, row in imp_df.head(10).iterrows():
            print(f"  {row['feature']:<25}: {row['importance']}")
        sys.stdout.flush()

    # 6. Two-Stage Threshold Search on Validation Set
    print("\n--> [6/6] Two-Stage Threshold Search on Macro F_0.5...")
    sys.stdout.flush()

    df_X_val = pd.DataFrame([r[2] for r in val_pair_records])
    val_probs = clf.predict_proba(df_X_val[feature_cols])[:, 1]

    val_preds_by_s1 = defaultdict(list)
    for (s1_id, cid, _, _), prob in zip(val_pair_records, val_probs):
        val_preds_by_s1[s1_id].append((cid, float(prob)))

    # A. Coarse Search: 0.30 to 0.95 with step 0.01
    print("Stage 1: Coarse Grid Search (0.30 to 0.95, step 0.01)...")
    sys.stdout.flush()
    best_coarse_th = 0.50
    best_coarse_score = -1.0

    coarse_grid = np.linspace(0.30, 0.95, 66)
    for th in coarse_grid:
        score = compute_macro_f05(val_preds_by_s1, gt_map, val_s1_ids, th)
        if score > best_coarse_score:
            best_coarse_score = score
            best_coarse_th = th

    print(f"  Coarse Optimum: Macro F_0.5 = {best_coarse_score:.4f} at threshold = {best_coarse_th:.3f}")
    sys.stdout.flush()

    # B. Fine Search: [best - 0.03, best + 0.03] with step 0.001
    print("Stage 2: Fine Grid Search (+/- 0.03 around optimum, step 0.001)...")
    sys.stdout.flush()
    fine_grid = np.linspace(best_coarse_th - 0.03, best_coarse_th + 0.03, 61)
    best_fine_th = best_coarse_th
    best_fine_score = best_coarse_score

    for th in fine_grid:
        score = compute_macro_f05(val_preds_by_s1, gt_map, val_s1_ids, th)
        if score > best_fine_score:
            best_fine_score = score
            best_fine_th = th

    print("\n" + "="*70)
    print("STEP 5 FINAL LEAK-FREE VALIDATION RESULTS:")
    print("="*70)
    print(f"  Blind Candidate Recall:      {blind_recall_pct:.2f}% ({total_val_found}/{total_val_true})")
    print(f"  Average Candidate Pairs:     {avg_cands_val:.1f} per S1 entity")
    print(f"  Training Pairs:              {len(X_train):,} (Pos={pos_train:,}, Neg={neg_train:,})")
    print(f"  Positive / Negative Ratio:   1 : {neg_train/max(1, pos_train):.1f}")
    print(f"  Optimal Decision Threshold:  {best_fine_th:.4f}")
    print(f"  Validation Macro F_0.5:      {best_fine_score:.4f}")
    print("="*70)
    sys.stdout.flush()

if __name__ == "__main__":
    main()
